version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4mjnypml9k8m"
s3_prefix = "patientapi"
region = "ap-south-1"
profile = "hiyadav-root"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
