AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-lambda

  Sample SAM Template for hello-lambda
Globals:
  Function:
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 30

Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patient-checkout-api
      Handler: com.aws.lambda.api.PatientChekoutService::handler
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutDLQ
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events: # it will bind the api-gateway that will be created by SAM with the lambda function
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  PatientBillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout-api
      Handler: com.aws.lambda.api.PatientBillService::handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
  ErrorHandlingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout-api
      Handler: com.aws.lambda.api.ErrorHandler::handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutDLQ