AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-lambda

  Sample SAM Template for hello-lambda
Globals:
  Function:
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: OrderServiceApi
      Handler: com.aws.lambda.api.OrderService::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events: # it will bind the api-gateway that will be created by SAM with the lambda function
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: OrderServiceApi
      Handler: com.aws.lambda.api.ReadOrderService::getOrder
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events: # it will bind the api-gateway that will be created by SAM with the lambda function
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
Outputs: #to get additional info like the api-url from apigateway
  CreateOrdersAPI:
    Description: "API Gateway endpoint url for create orders function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CreateOrderFunction:
    Description: "Create Order Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create Order Lambda Function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn