AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-lambda

  Sample SAM Template for hello-lambda new

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  SimpleHello:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SimpleHello
      Handler: com.aws.lambda.SimplyHello::coldStartBasic
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          restapiurl: testurl
      #Timeout: 6 --> we can override the default timeout
      